package entities.job_offer;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import entities.User;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Timestamp;

/**
 * JobApplication generated by hbm2java
 */
@Entity
@Table(name="job_application"
    , uniqueConstraints = @UniqueConstraint(columnNames={"offer_id", "student_id"})
    , indexes = {
        @Index(name = "idx_app_status", columnList = "status"),
        @Index(name = "idx_app_created_at", columnList = "created_at"),
        @Index(name = "idx_student_id", columnList = "student_id"),
        @Index(name = "idx_offer_id", columnList = "offer_id")
    }
)
public class JobApplication  implements java.io.Serializable {


     private int id;
     private User user;
     private JobOffer jobOffer;
     private String message;
     private String cvFileName;
     private String status;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private Integer score;
     private String scoreBreakdown;
     private Timestamp scoredAt;
     private String extractedData;
     private Byte statusNotified;
     private Timestamp statusNotifiedAt;
     private String statusMessage;

    public JobApplication() {
    }

	
    public JobApplication(int id, User user, JobOffer jobOffer, String status, Timestamp createdAt) {
        this.id = id;
        this.user = user;
        this.jobOffer = jobOffer;
        this.status = status;
        this.createdAt = createdAt;
    }
    public JobApplication(int id, User user, JobOffer jobOffer, String message, String cvFileName, String status, Timestamp createdAt, Timestamp updatedAt, Integer score, String scoreBreakdown, Timestamp scoredAt, String extractedData, Byte statusNotified, Timestamp statusNotifiedAt, String statusMessage) {
       this.id = id;
       this.user = user;
       this.jobOffer = jobOffer;
       this.message = message;
       this.cvFileName = cvFileName;
       this.status = status;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.score = score;
       this.scoreBreakdown = scoreBreakdown;
       this.scoredAt = scoredAt;
       this.extractedData = extractedData;
       this.statusNotified = statusNotified;
       this.statusNotifiedAt = statusNotifiedAt;
       this.statusMessage = statusMessage;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="offer_id", nullable=false)
    public JobOffer getJobOffer() {
        return this.jobOffer;
    }
    
    public void setJobOffer(JobOffer jobOffer) {
        this.jobOffer = jobOffer;
    }

    
    @Column(name="message")
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="cv_file_name", length=255)
    public String getCvFileName() {
        return this.cvFileName;
    }
    
    public void setCvFileName(String cvFileName) {
        this.cvFileName = cvFileName;
    }

    
    @Column(name="status", nullable=false, length=255)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    
    @Column(name="score")
    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }

    
    @Column(name="score_breakdown", length=1073741824)
    public String getScoreBreakdown() {
        return this.scoreBreakdown;
    }
    
    public void setScoreBreakdown(String scoreBreakdown) {
        this.scoreBreakdown = scoreBreakdown;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="scored_at", length=19)
    public Timestamp getScoredAt() {
        return this.scoredAt;
    }
    
    public void setScoredAt(Timestamp scoredAt) {
        this.scoredAt = scoredAt;
    }

    
    @Column(name="extracted_data", length=1073741824)
    public String getExtractedData() {
        return this.extractedData;
    }
    
    public void setExtractedData(String extractedData) {
        this.extractedData = extractedData;
    }

    
    @Column(name="status_notified")
    public Byte getStatusNotified() {
        return this.statusNotified;
    }
    
    public void setStatusNotified(Byte statusNotified) {
        this.statusNotified = statusNotified;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="status_notified_at", length=19)
    public Timestamp getStatusNotifiedAt() {
        return this.statusNotifiedAt;
    }
    
    public void setStatusNotifiedAt(Timestamp statusNotifiedAt) {
        this.statusNotifiedAt = statusNotifiedAt;
    }

    
    @Column(name="status_message")
    public String getStatusMessage() {
        return this.statusMessage;
    }
    
    public void setStatusMessage(String statusMessage) {
        this.statusMessage = statusMessage;
    }




}


