package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Answer generated by hbm2java
 */
@Entity
@Table(name="answer"
)
public class Answer  implements java.io.Serializable {


     private int id;
     private Choice choice;
     private UserAnswer userAnswer;
     private Question question;
     private String textAnswer;
     private byte isCorrect;
     private Integer pointsEarned;

    public Answer() {
    }

	
    public Answer(int id, UserAnswer userAnswer, Question question, byte isCorrect) {
        this.id = id;
        this.userAnswer = userAnswer;
        this.question = question;
        this.isCorrect = isCorrect;
    }
    public Answer(int id, Choice choice, UserAnswer userAnswer, Question question, String textAnswer, byte isCorrect, Integer pointsEarned) {
       this.id = id;
       this.choice = choice;
       this.userAnswer = userAnswer;
       this.question = question;
       this.textAnswer = textAnswer;
       this.isCorrect = isCorrect;
       this.pointsEarned = pointsEarned;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="selected_choice_id")
    public Choice getChoice() {
        return this.choice;
    }
    
    public void setChoice(Choice choice) {
        this.choice = choice;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_answer_id", nullable=false)
    public UserAnswer getUserAnswer() {
        return this.userAnswer;
    }
    
    public void setUserAnswer(UserAnswer userAnswer) {
        this.userAnswer = userAnswer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="question_id", nullable=false)
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }

    
    @Column(name="text_answer")
    public String getTextAnswer() {
        return this.textAnswer;
    }
    
    public void setTextAnswer(String textAnswer) {
        this.textAnswer = textAnswer;
    }

    
    @Column(name="is_correct", nullable=false)
    public byte getIsCorrect() {
        return this.isCorrect;
    }
    
    public void setIsCorrect(byte isCorrect) {
        this.isCorrect = isCorrect;
    }

    
    @Column(name="points_earned")
    public Integer getPointsEarned() {
        return this.pointsEarned;
    }
    
    public void setPointsEarned(Integer pointsEarned) {
        this.pointsEarned = pointsEarned;
    }




}


