package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Answer generated by hbm2java
 */
@Entity
@Table(name="answer"
)
public class Answer  implements java.io.Serializable {


     private Integer id;
     private Choice choice;
     private UserAnswer userAnswer;
     private Question question;
     private String textAnswer;
     private byte isCorrect;
     private Integer pointsEarned;
     private Double aiDetectionScore;
     private String aiDetectionResult;

    public Answer() {
    }

	
    public Answer(UserAnswer userAnswer, Question question, byte isCorrect) {
        this.userAnswer = userAnswer;
        this.question = question;
        this.isCorrect = isCorrect;
    }
    public Answer(Choice choice, UserAnswer userAnswer, Question question, String textAnswer, byte isCorrect, Integer pointsEarned, Double aiDetectionScore, String aiDetectionResult) {
       this.choice = choice;
       this.userAnswer = userAnswer;
       this.question = question;
       this.textAnswer = textAnswer;
       this.isCorrect = isCorrect;
       this.pointsEarned = pointsEarned;
       this.aiDetectionScore = aiDetectionScore;
       this.aiDetectionResult = aiDetectionResult;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="selected_choice_id")
    public Choice getChoice() {
        return this.choice;
    }
    
    public void setChoice(Choice choice) {
        this.choice = choice;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_answer_id", nullable=false)
    public UserAnswer getUserAnswer() {
        return this.userAnswer;
    }
    
    public void setUserAnswer(UserAnswer userAnswer) {
        this.userAnswer = userAnswer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="question_id", nullable=false)
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }

    
    @Column(name="text_answer")
    public String getTextAnswer() {
        return this.textAnswer;
    }
    
    public void setTextAnswer(String textAnswer) {
        this.textAnswer = textAnswer;
    }

    
    @Column(name="is_correct", nullable=false)
    public byte getIsCorrect() {
        return this.isCorrect;
    }
    
    public void setIsCorrect(byte isCorrect) {
        this.isCorrect = isCorrect;
    }

    
    @Column(name="points_earned")
    public Integer getPointsEarned() {
        return this.pointsEarned;
    }
    
    public void setPointsEarned(Integer pointsEarned) {
        this.pointsEarned = pointsEarned;
    }

    
    @Column(name="ai_detection_score", precision=22)
    public Double getAiDetectionScore() {
        return this.aiDetectionScore;
    }
    
    public void setAiDetectionScore(Double aiDetectionScore) {
        this.aiDetectionScore = aiDetectionScore;
    }

    
    @Column(name="ai_detection_result")
    public String getAiDetectionResult() {
        return this.aiDetectionResult;
    }
    
    public void setAiDetectionResult(String aiDetectionResult) {
        this.aiDetectionResult = aiDetectionResult;
    }




}


