package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * BuildProgramModule generated by hbm2java
 */
@Entity
@Table(name="build_program_module"
    , uniqueConstraints = @UniqueConstraint(columnNames={"build_program_id", "module_id"}) 
)
public class BuildProgramModule  implements java.io.Serializable {


     private int id;
     private BuildProgram buildProgram;
     private Module module;
     private Set<BuildProgramCourse> buildProgramCourses = new HashSet<BuildProgramCourse>(0);

    public BuildProgramModule() {
    }

	
    public BuildProgramModule(int id, BuildProgram buildProgram, Module module) {
        this.id = id;
        this.buildProgram = buildProgram;
        this.module = module;
    }
    public BuildProgramModule(int id, BuildProgram buildProgram, Module module, Set<BuildProgramCourse> buildProgramCourses) {
       this.id = id;
       this.buildProgram = buildProgram;
       this.module = module;
       this.buildProgramCourses = buildProgramCourses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="build_program_id", nullable=false)
    public BuildProgram getBuildProgram() {
        return this.buildProgram;
    }
    
    public void setBuildProgram(BuildProgram buildProgram) {
        this.buildProgram = buildProgram;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="module_id", nullable=false)
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="buildProgramModule")
    public Set<BuildProgramCourse> getBuildProgramCourses() {
        return this.buildProgramCourses;
    }
    
    public void setBuildProgramCourses(Set<BuildProgramCourse> buildProgramCourses) {
        this.buildProgramCourses = buildProgramCourses;
    }




}


