package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * BuildProgram generated by hbm2java
 */
@Entity
@Table(name="build_program"
)
public class BuildProgram  implements java.io.Serializable {


     private int id;
     private Program program;
     private Date startDate;
     private Date endDate;
     private String imageUrl;
     private String level;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private Set<BuildProgramModule> buildProgramModules = new HashSet<BuildProgramModule>(0);

    public BuildProgram() {
    }

	
    public BuildProgram(int id, Program program, Date startDate, Date endDate, String level, Timestamp createdAt, Timestamp updatedAt) {
        this.id = id;
        this.program = program;
        this.startDate = startDate;
        this.endDate = endDate;
        this.level = level;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public BuildProgram(int id, Program program, Date startDate, Date endDate, String imageUrl, String level, Timestamp createdAt, Timestamp updatedAt, Set<BuildProgramModule> buildProgramModules) {
       this.id = id;
       this.program = program;
       this.startDate = startDate;
       this.endDate = endDate;
       this.imageUrl = imageUrl;
       this.level = level;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.buildProgramModules = buildProgramModules;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="program_id", nullable=false)
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", nullable=false, length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="end_date", nullable=false, length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="image_url", length=255)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    @Column(name="level", nullable=false, length=50)
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="buildProgram")
    public Set<BuildProgramModule> getBuildProgramModules() {
        return this.buildProgramModules;
    }
    
    public void setBuildProgramModules(Set<BuildProgramModule> buildProgramModules) {
        this.buildProgramModules = buildProgramModules;
    }




}


