package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * BuildProgramCourse generated by hbm2java
 */
@Entity
@Table(name="build_program_course"
    , uniqueConstraints = @UniqueConstraint(columnNames={"build_program_module_id", "course_id"}) 
)
public class BuildProgramCourse  implements java.io.Serializable {


     private Integer id;
     private BuildProgramModule buildProgramModule;
     private Course course;
     private Set<BuildProgramContenu> buildProgramContenus = new HashSet<BuildProgramContenu>(0);

    public BuildProgramCourse() {
    }

	
    public BuildProgramCourse(BuildProgramModule buildProgramModule, Course course) {
        this.buildProgramModule = buildProgramModule;
        this.course = course;
    }
    public BuildProgramCourse(BuildProgramModule buildProgramModule, Course course, Set<BuildProgramContenu> buildProgramContenus) {
       this.buildProgramModule = buildProgramModule;
       this.course = course;
       this.buildProgramContenus = buildProgramContenus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="build_program_module_id", nullable=false)
    public BuildProgramModule getBuildProgramModule() {
        return this.buildProgramModule;
    }
    
    public void setBuildProgramModule(BuildProgramModule buildProgramModule) {
        this.buildProgramModule = buildProgramModule;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_id", nullable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="buildProgramCourse")
    public Set<BuildProgramContenu> getBuildProgramContenus() {
        return this.buildProgramContenus;
    }
    
    public void setBuildProgramContenus(Set<BuildProgramContenu> buildProgramContenus) {
        this.buildProgramContenus = buildProgramContenus;
    }




}


