package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * BuildProgramContenu generated by hbm2java
 */
@Entity
@Table(name="build_program_contenu"
    , uniqueConstraints = @UniqueConstraint(columnNames={"build_program_course_id", "contenu_id"}) 
)
public class BuildProgramContenu  implements java.io.Serializable {


     private Integer id;
     private Contenu contenu;
     private BuildProgramCourse buildProgramCourse;

    public BuildProgramContenu() {
    }

    public BuildProgramContenu(Contenu contenu, BuildProgramCourse buildProgramCourse) {
       this.contenu = contenu;
       this.buildProgramCourse = buildProgramCourse;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contenu_id", nullable=false)
    public Contenu getContenu() {
        return this.contenu;
    }
    
    public void setContenu(Contenu contenu) {
        this.contenu = contenu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="build_program_course_id", nullable=false)
    public BuildProgramCourse getBuildProgramCourse() {
        return this.buildProgramCourse;
    }
    
    public void setBuildProgramCourse(BuildProgramCourse buildProgramCourse) {
        this.buildProgramCourse = buildProgramCourse;
    }




}


