package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Choice generated by hbm2java
 */
@Entity
@Table(name="choice"
)
public class Choice  implements java.io.Serializable {


     private Integer id;
     private Question question;
     private String choiceText;
     private byte isCorrect;
     private int position;
     private Set<Answer> answers = new HashSet<Answer>(0);

    public Choice() {
    }

	
    public Choice(Question question, String choiceText, byte isCorrect, int position) {
        this.question = question;
        this.choiceText = choiceText;
        this.isCorrect = isCorrect;
        this.position = position;
    }
    public Choice(Question question, String choiceText, byte isCorrect, int position, Set<Answer> answers) {
       this.question = question;
       this.choiceText = choiceText;
       this.isCorrect = isCorrect;
       this.position = position;
       this.answers = answers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="question_id", nullable=false)
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }

    
    @Column(name="choice_text", nullable=false)
    public String getChoiceText() {
        return this.choiceText;
    }
    
    public void setChoiceText(String choiceText) {
        this.choiceText = choiceText;
    }

    
    @Column(name="is_correct", nullable=false)
    public byte getIsCorrect() {
        return this.isCorrect;
    }
    
    public void setIsCorrect(byte isCorrect) {
        this.isCorrect = isCorrect;
    }

    
    @Column(name="position", nullable=false)
    public int getPosition() {
        return this.position;
    }
    
    public void setPosition(int position) {
        this.position = position;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="choice")
    public Set<Answer> getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Set<Answer> answers) {
        this.answers = answers;
    }




}


