package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * ClasseModule generated by hbm2java
 */
@Entity
@Table(name="classe_module"
    , uniqueConstraints = @UniqueConstraint(columnNames={"classe_id", "module_id"}) 
)
public class ClasseModule  implements java.io.Serializable {


     private Integer id;
     private Classe classe;
     private Module module;
     private Set<ClasseCourse> classeCourses = new HashSet<ClasseCourse>(0);

    public ClasseModule() {
    }

	
    public ClasseModule(Classe classe, Module module) {
        this.classe = classe;
        this.module = module;
    }
    public ClasseModule(Classe classe, Module module, Set<ClasseCourse> classeCourses) {
       this.classe = classe;
       this.module = module;
       this.classeCourses = classeCourses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="classe_id", nullable=false)
    public Classe getClasse() {
        return this.classe;
    }
    
    public void setClasse(Classe classe) {
        this.classe = classe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="module_id", nullable=false)
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classeModule")
    public Set<ClasseCourse> getClasseCourses() {
        return this.classeCourses;
    }
    
    public void setClasseCourses(Set<ClasseCourse> classeCourses) {
        this.classeCourses = classeCourses;
    }




}


