package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * ClasseCourse generated by hbm2java
 */
@Entity
@Table(name="classe_course"
    , uniqueConstraints = @UniqueConstraint(columnNames={"classe_module_id", "course_id"}) 
)
public class ClasseCourse  implements java.io.Serializable {


     private Integer id;
     private Course course;
     private ClasseModule classeModule;
     private byte isHidden;
     private Set<ClasseContenu> classeContenus = new HashSet<ClasseContenu>(0);

    public ClasseCourse() {
    }

	
    public ClasseCourse(Course course, ClasseModule classeModule, byte isHidden) {
        this.course = course;
        this.classeModule = classeModule;
        this.isHidden = isHidden;
    }
    public ClasseCourse(Course course, ClasseModule classeModule, byte isHidden, Set<ClasseContenu> classeContenus) {
       this.course = course;
       this.classeModule = classeModule;
       this.isHidden = isHidden;
       this.classeContenus = classeContenus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_id", nullable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="classe_module_id", nullable=false)
    public ClasseModule getClasseModule() {
        return this.classeModule;
    }
    
    public void setClasseModule(ClasseModule classeModule) {
        this.classeModule = classeModule;
    }

    
    @Column(name="is_hidden", nullable=false)
    public byte getIsHidden() {
        return this.isHidden;
    }
    
    public void setIsHidden(byte isHidden) {
        this.isHidden = isHidden;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classeCourse")
    public Set<ClasseContenu> getClasseContenus() {
        return this.classeContenus;
    }
    
    public void setClasseContenus(Set<ClasseContenu> classeContenus) {
        this.classeContenus = classeContenus;
    }




}


