package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * ClassMeeting generated by hbm2java
 */
@Entity
@Table(name="class_meeting"
)
public class ClassMeeting  implements java.io.Serializable {


     private int id;
     private TeacherClasse teacherClasse;
     private String title;
     private String description;
     private String roomCode;
     private String status;
     private Timestamp scheduledAt;
     private Timestamp startedAt;
     private Timestamp endedAt;
     private Timestamp createdAt;

    public ClassMeeting() {
    }

	
    public ClassMeeting(int id, TeacherClasse teacherClasse, String title, String roomCode, String status, Timestamp createdAt) {
        this.id = id;
        this.teacherClasse = teacherClasse;
        this.title = title;
        this.roomCode = roomCode;
        this.status = status;
        this.createdAt = createdAt;
    }
    public ClassMeeting(int id, TeacherClasse teacherClasse, String title, String description, String roomCode, String status, Timestamp scheduledAt, Timestamp startedAt, Timestamp endedAt, Timestamp createdAt) {
       this.id = id;
       this.teacherClasse = teacherClasse;
       this.title = title;
       this.description = description;
       this.roomCode = roomCode;
       this.status = status;
       this.scheduledAt = scheduledAt;
       this.startedAt = startedAt;
       this.endedAt = endedAt;
       this.createdAt = createdAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="teacher_classe_id", nullable=false)
    public TeacherClasse getTeacherClasse() {
        return this.teacherClasse;
    }
    
    public void setTeacherClasse(TeacherClasse teacherClasse) {
        this.teacherClasse = teacherClasse;
    }

    
    @Column(name="title", nullable=false, length=255)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="room_code", nullable=false, length=100)
    public String getRoomCode() {
        return this.roomCode;
    }
    
    public void setRoomCode(String roomCode) {
        this.roomCode = roomCode;
    }

    
    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="scheduled_at", length=19)
    public Timestamp getScheduledAt() {
        return this.scheduledAt;
    }
    
    public void setScheduledAt(Timestamp scheduledAt) {
        this.scheduledAt = scheduledAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="started_at", length=19)
    public Timestamp getStartedAt() {
        return this.startedAt;
    }
    
    public void setStartedAt(Timestamp startedAt) {
        this.startedAt = startedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ended_at", length=19)
    public Timestamp getEndedAt() {
        return this.endedAt;
    }
    
    public void setEndedAt(Timestamp endedAt) {
        this.endedAt = endedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }




}


