package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Classe generated by hbm2java
 */
@Entity
@Table(name="classe"
)
public class Classe  implements java.io.Serializable {


     private int id;
     private Program program;
     private String name;
     private Date startDate;
     private Date endDate;
     private String imageUrl;
     private String status;
     private int capacity;
     private String level;
     private String specialty;
     private Set<CourseDocument> courseDocuments = new HashSet<CourseDocument>(0);
     private Set<Schedule> schedules = new HashSet<Schedule>(0);
     private Set<StudentClasse> studentClasses = new HashSet<StudentClasse>(0);
     private Set<TeacherClasse> teacherClasses = new HashSet<TeacherClasse>(0);
     private Set<ClasseModule> classeModules = new HashSet<ClasseModule>(0);
     private Set<Assessment> assessments = new HashSet<Assessment>(0);

    public Classe() {
    }

	
    public Classe(int id, Program program, String name, Date startDate, Date endDate, String status, int capacity, String level, String specialty) {
        this.id = id;
        this.program = program;
        this.name = name;
        this.startDate = startDate;
        this.endDate = endDate;
        this.status = status;
        this.capacity = capacity;
        this.level = level;
        this.specialty = specialty;
    }
    public Classe(int id, Program program, String name, Date startDate, Date endDate, String imageUrl, String status, int capacity, String level, String specialty, Set<CourseDocument> courseDocuments, Set<Schedule> schedules, Set<StudentClasse> studentClasses, Set<TeacherClasse> teacherClasses, Set<ClasseModule> classeModules, Set<Assessment> assessments) {
       this.id = id;
       this.program = program;
       this.name = name;
       this.startDate = startDate;
       this.endDate = endDate;
       this.imageUrl = imageUrl;
       this.status = status;
       this.capacity = capacity;
       this.level = level;
       this.specialty = specialty;
       this.courseDocuments = courseDocuments;
       this.schedules = schedules;
       this.studentClasses = studentClasses;
       this.teacherClasses = teacherClasses;
       this.classeModules = classeModules;
       this.assessments = assessments;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="program_id", nullable=false)
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", nullable=false, length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="end_date", nullable=false, length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    
    @Column(name="image_url", length=255)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    @Column(name="status", nullable=false, length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="capacity", nullable=false)
    public int getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

    
    @Column(name="level", nullable=false, length=10)
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }

    
    @Column(name="specialty", nullable=false, length=50)
    public String getSpecialty() {
        return this.specialty;
    }
    
    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classe")
    public Set<CourseDocument> getCourseDocuments() {
        return this.courseDocuments;
    }
    
    public void setCourseDocuments(Set<CourseDocument> courseDocuments) {
        this.courseDocuments = courseDocuments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classe")
    public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classe")
    public Set<StudentClasse> getStudentClasses() {
        return this.studentClasses;
    }
    
    public void setStudentClasses(Set<StudentClasse> studentClasses) {
        this.studentClasses = studentClasses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classe")
    public Set<TeacherClasse> getTeacherClasses() {
        return this.teacherClasses;
    }
    
    public void setTeacherClasses(Set<TeacherClasse> teacherClasses) {
        this.teacherClasses = teacherClasses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classe")
    public Set<ClasseModule> getClasseModules() {
        return this.classeModules;
    }
    
    public void setClasseModules(Set<ClasseModule> classeModules) {
        this.classeModules = classeModules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classe")
    public Set<Assessment> getAssessments() {
        return this.assessments;
    }
    
    public void setAssessments(Set<Assessment> assessments) {
        this.assessments = assessments;
    }




}


