package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * ClasseContenu generated by hbm2java
 */
@Entity
@Table(name="classe_contenu"
    , uniqueConstraints = @UniqueConstraint(columnNames={"classe_course_id", "contenu_id"}) 
)
public class ClasseContenu  implements java.io.Serializable {


     private Integer id;
     private Contenu contenu;
     private ClasseCourse classeCourse;
     private byte isHidden;

    public ClasseContenu() {
    }

    public ClasseContenu(Contenu contenu, ClasseCourse classeCourse, byte isHidden) {
       this.contenu = contenu;
       this.classeCourse = classeCourse;
       this.isHidden = isHidden;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contenu_id", nullable=false)
    public Contenu getContenu() {
        return this.contenu;
    }
    
    public void setContenu(Contenu contenu) {
        this.contenu = contenu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="classe_course_id", nullable=false)
    public ClasseCourse getClasseCourse() {
        return this.classeCourse;
    }
    
    public void setClasseCourse(ClasseCourse classeCourse) {
        this.classeCourse = classeCourse;
    }

    
    @Column(name="is_hidden", nullable=false)
    public byte getIsHidden() {
        return this.isHidden;
    }
    
    public void setIsHidden(byte isHidden) {
        this.isHidden = isHidden;
    }




}


