package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Contenu generated by hbm2java
 */
@Entity
@Table(name="contenu"
)
public class Contenu  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String fileName;
     private String fileType;
     private String type;
     private byte published;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private Integer fileSize;
     private Set<BuildProgramContenu> buildProgramContenus = new HashSet<BuildProgramContenu>(0);
     private Set<ClasseContenu> classeContenus = new HashSet<ClasseContenu>(0);
     private Set<Assessment> assessments = new HashSet<Assessment>(0);
     private Set<Quiz> quizs = new HashSet<Quiz>(0);
     private Set<CourseContenu> courseContenus = new HashSet<CourseContenu>(0);

    public Contenu() {
    }

	
    public Contenu(Integer id, String title, String type, byte published, Timestamp createdAt, Timestamp updatedAt) {
        this.id = id;
        this.title = title;
        this.type = type;
        this.published = published;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Contenu(Integer id, String title, String fileName, String fileType, String type, byte published, Timestamp createdAt, Timestamp updatedAt, Integer fileSize, Set<BuildProgramContenu> buildProgramContenus, Set<ClasseContenu> classeContenus, Set<Assessment> assessments, Set<Quiz> quizs, Set<CourseContenu> courseContenus) {
       this.id = id;
       this.title = title;
       this.fileName = fileName;
       this.fileType = fileType;
       this.type = type;
       this.published = published;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.fileSize = fileSize;
       this.buildProgramContenus = buildProgramContenus;
       this.classeContenus = classeContenus;
       this.assessments = assessments;
       this.quizs = quizs;
       this.courseContenus = courseContenus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="title", nullable=false, length=255)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="file_name", length=255)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="file_type", length=255)
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    
    @Column(name="type", nullable=false, length=255)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="published", nullable=false)
    public byte getPublished() {
        return this.published;
    }
    
    public void setPublished(byte published) {
        this.published = published;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    
    @Column(name="file_size")
    public Integer getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contenu")
    public Set<BuildProgramContenu> getBuildProgramContenus() {
        return this.buildProgramContenus;
    }
    
    public void setBuildProgramContenus(Set<BuildProgramContenu> buildProgramContenus) {
        this.buildProgramContenus = buildProgramContenus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contenu")
    public Set<ClasseContenu> getClasseContenus() {
        return this.classeContenus;
    }
    
    public void setClasseContenus(Set<ClasseContenu> classeContenus) {
        this.classeContenus = classeContenus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contenu")
    public Set<Assessment> getAssessments() {
        return this.assessments;
    }
    
    public void setAssessments(Set<Assessment> assessments) {
        this.assessments = assessments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contenu")
    public Set<Quiz> getQuizs() {
        return this.quizs;
    }
    
    public void setQuizs(Set<Quiz> quizs) {
        this.quizs = quizs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contenu")
    public Set<CourseContenu> getCourseContenus() {
        return this.courseContenus;
    }
    
    public void setCourseContenus(Set<CourseContenu> courseContenus) {
        this.courseContenus = courseContenus;
    }




}


