package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name="course"
)
public class Course  implements java.io.Serializable {


     private Integer id;
     private String title;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private Set<Schedule> schedules = new HashSet<Schedule>(0);
     private Set<ClasseCourse> classeCourses = new HashSet<ClasseCourse>(0);
     private Set<Assessment> assessments = new HashSet<Assessment>(0);
     private Set<CourseContenu> courseContenus = new HashSet<CourseContenu>(0);
     private Set<ModuleCourse> moduleCourses = new HashSet<ModuleCourse>(0);
     private Set<Reclamation> reclamations = new HashSet<Reclamation>(0);
     private Set<BuildProgramCourse> buildProgramCourses = new HashSet<BuildProgramCourse>(0);

    public Course() {
    }

	
    public Course(String title, Timestamp createdAt, Timestamp updatedAt) {
        this.title = title;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Course(String title, Timestamp createdAt, Timestamp updatedAt, Set<Schedule> schedules, Set<ClasseCourse> classeCourses, Set<Assessment> assessments, Set<CourseContenu> courseContenus, Set<ModuleCourse> moduleCourses, Set<Reclamation> reclamations, Set<BuildProgramCourse> buildProgramCourses) {
       this.title = title;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.schedules = schedules;
       this.classeCourses = classeCourses;
       this.assessments = assessments;
       this.courseContenus = courseContenus;
       this.moduleCourses = moduleCourses;
       this.reclamations = reclamations;
       this.buildProgramCourses = buildProgramCourses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="title", nullable=false, length=255)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<ClasseCourse> getClasseCourses() {
        return this.classeCourses;
    }
    
    public void setClasseCourses(Set<ClasseCourse> classeCourses) {
        this.classeCourses = classeCourses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<Assessment> getAssessments() {
        return this.assessments;
    }
    
    public void setAssessments(Set<Assessment> assessments) {
        this.assessments = assessments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<CourseContenu> getCourseContenus() {
        return this.courseContenus;
    }
    
    public void setCourseContenus(Set<CourseContenu> courseContenus) {
        this.courseContenus = courseContenus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<ModuleCourse> getModuleCourses() {
        return this.moduleCourses;
    }
    
    public void setModuleCourses(Set<ModuleCourse> moduleCourses) {
        this.moduleCourses = moduleCourses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<Reclamation> getReclamations() {
        return this.reclamations;
    }
    
    public void setReclamations(Set<Reclamation> reclamations) {
        this.reclamations = reclamations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<BuildProgramCourse> getBuildProgramCourses() {
        return this.buildProgramCourses;
    }
    
    public void setBuildProgramCourses(Set<BuildProgramCourse> buildProgramCourses) {
        this.buildProgramCourses = buildProgramCourses;
    }




}


