package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * CourseContenu generated by hbm2java
 */
@Entity
@Table(name="course_contenu"
    , uniqueConstraints = @UniqueConstraint(columnNames={"course_id", "contenu_id"}) 
)
public class CourseContenu  implements java.io.Serializable {


     private Integer id;
     private Contenu contenu;
     private Course course;
     private int position;

    public CourseContenu() {
    }

    public CourseContenu(Contenu contenu, Course course, int position) {
       this.contenu = contenu;
       this.course = course;
       this.position = position;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contenu_id", nullable=false)
    public Contenu getContenu() {
        return this.contenu;
    }
    
    public void setContenu(Contenu contenu) {
        this.contenu = contenu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_id", nullable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

    
    @Column(name="position", nullable=false)
    public int getPosition() {
        return this.position;
    }
    
    public void setPosition(int position) {
        this.position = position;
    }




}


