package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * CourseDocument generated by hbm2java
 */
@Entity
@Table(name="course_document"
)
public class CourseDocument  implements java.io.Serializable {


     private int id;
     private User user;
     private Classe classe;
     private String title;
     private String description;
     private String fileName;
     private String originalFileName;
     private Integer fileSize;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private byte isActive;

    public CourseDocument() {
    }

	
    public CourseDocument(int id, User user, Classe classe, String title, Timestamp createdAt, Timestamp updatedAt, byte isActive) {
        this.id = id;
        this.user = user;
        this.classe = classe;
        this.title = title;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.isActive = isActive;
    }
    public CourseDocument(int id, User user, Classe classe, String title, String description, String fileName, String originalFileName, Integer fileSize, Timestamp createdAt, Timestamp updatedAt, byte isActive) {
       this.id = id;
       this.user = user;
       this.classe = classe;
       this.title = title;
       this.description = description;
       this.fileName = fileName;
       this.originalFileName = originalFileName;
       this.fileSize = fileSize;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.isActive = isActive;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="uploaded_by_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="classe_id", nullable=false)
    public Classe getClasse() {
        return this.classe;
    }
    
    public void setClasse(Classe classe) {
        this.classe = classe;
    }

    
    @Column(name="title", nullable=false, length=255)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="file_name", length=255)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="original_file_name", length=255)
    public String getOriginalFileName() {
        return this.originalFileName;
    }
    
    public void setOriginalFileName(String originalFileName) {
        this.originalFileName = originalFileName;
    }

    
    @Column(name="file_size")
    public Integer getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(Integer fileSize) {
        this.fileSize = fileSize;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    
    @Column(name="is_active", nullable=false)
    public byte getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(byte isActive) {
        this.isActive = isActive;
    }




}


