package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * DoctrineMigrationVersions generated by hbm2java
 */
@Entity
@Table(name="doctrine_migration_versions"
)
public class DoctrineMigrationVersions  implements java.io.Serializable {


     private String version;
     private Timestamp executedAt;
     private Integer executionTime;

    public DoctrineMigrationVersions() {
    }

	
    public DoctrineMigrationVersions(String version) {
        this.version = version;
    }
    public DoctrineMigrationVersions(String version, Timestamp executedAt, Integer executionTime) {
       this.version = version;
       this.executedAt = executedAt;
       this.executionTime = executionTime;
    }
   
     @Id 

    
    @Column(name="version", unique=true, nullable=false, length=191)
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="executed_at", length=19)
    public Timestamp getExecutedAt() {
        return this.executedAt;
    }
    
    public void setExecutedAt(Timestamp executedAt) {
        this.executedAt = executedAt;
    }

    
    @Column(name="execution_time")
    public Integer getExecutionTime() {
        return this.executionTime;
    }
    
    public void setExecutionTime(Integer executionTime) {
        this.executionTime = executionTime;
    }




}


