package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * DocumentRequest generated by hbm2java
 */
@Entity
@Table(name="document_request"
)
public class DocumentRequest  implements java.io.Serializable {


     private int id;
     private User user;
     private String documentType;
     private String additionalInfo;
     private String status;
     private Timestamp requestedAt;
     private Timestamp deliveredAt;
     private String documentPath;

    public DocumentRequest() {
    }

	
    public DocumentRequest(int id, User user, String documentType, String status, Timestamp requestedAt) {
        this.id = id;
        this.user = user;
        this.documentType = documentType;
        this.status = status;
        this.requestedAt = requestedAt;
    }
    public DocumentRequest(int id, User user, String documentType, String additionalInfo, String status, Timestamp requestedAt, Timestamp deliveredAt, String documentPath) {
       this.id = id;
       this.user = user;
       this.documentType = documentType;
       this.additionalInfo = additionalInfo;
       this.status = status;
       this.requestedAt = requestedAt;
       this.deliveredAt = deliveredAt;
       this.documentPath = documentPath;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="document_type", nullable=false, length=100)
    public String getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(String documentType) {
        this.documentType = documentType;
    }

    
    @Column(name="additional_info")
    public String getAdditionalInfo() {
        return this.additionalInfo;
    }
    
    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }

    
    @Column(name="status", nullable=false, length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="requested_at", nullable=false, length=19)
    public Timestamp getRequestedAt() {
        return this.requestedAt;
    }
    
    public void setRequestedAt(Timestamp requestedAt) {
        this.requestedAt = requestedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="delivered_at", length=19)
    public Timestamp getDeliveredAt() {
        return this.deliveredAt;
    }
    
    public void setDeliveredAt(Timestamp deliveredAt) {
        this.deliveredAt = deliveredAt;
    }

    
    @Column(name="document_path", length=255)
    public String getDocumentPath() {
        return this.documentPath;
    }
    
    public void setDocumentPath(String documentPath) {
        this.documentPath = documentPath;
    }




}


