package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name="event"
)
public class Event  implements java.io.Serializable {


     private int id;
     private User user;
     private String title;
     private String type;
     private String description;
     private String location;
     private Timestamp startAt;
     private Integer capacity;
     private String status;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private Set<EventParticipation> eventParticipations = new HashSet<EventParticipation>(0);

    public Event() {
    }

	
    public Event(int id, User user, String title, String type, Timestamp startAt, String status, Timestamp createdAt, Timestamp updatedAt) {
        this.id = id;
        this.user = user;
        this.title = title;
        this.type = type;
        this.startAt = startAt;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Event(int id, User user, String title, String type, String description, String location, Timestamp startAt, Integer capacity, String status, Timestamp createdAt, Timestamp updatedAt, Set<EventParticipation> eventParticipations) {
       this.id = id;
       this.user = user;
       this.title = title;
       this.type = type;
       this.description = description;
       this.location = location;
       this.startAt = startAt;
       this.capacity = capacity;
       this.status = status;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.eventParticipations = eventParticipations;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="title", nullable=false, length=255)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="type", nullable=false, length=100)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="location", length=255)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_at", nullable=false, length=19)
    public Timestamp getStartAt() {
        return this.startAt;
    }
    
    public void setStartAt(Timestamp startAt) {
        this.startAt = startAt;
    }

    
    @Column(name="capacity")
    public Integer getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    
    @Column(name="status", nullable=false, length=255)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="event")
    public Set<EventParticipation> getEventParticipations() {
        return this.eventParticipations;
    }
    
    public void setEventParticipations(Set<EventParticipation> eventParticipations) {
        this.eventParticipations = eventParticipations;
    }




}


