package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * ForumAiSuggestion generated by hbm2java
 */
@Entity
@Table(name="forum_ai_suggestion"
)
public class ForumAiSuggestion  implements java.io.Serializable {


     private int id;
     private String questionHash;
     private String question;
     private String suggestions;
     private String aiResponse;
     private Timestamp createdAt;
     private Timestamp expiresAt;
     private int usageCount;

    public ForumAiSuggestion() {
    }

	
    public ForumAiSuggestion(int id, String questionHash, String question, String suggestions, Timestamp createdAt, Timestamp expiresAt, int usageCount) {
        this.id = id;
        this.questionHash = questionHash;
        this.question = question;
        this.suggestions = suggestions;
        this.createdAt = createdAt;
        this.expiresAt = expiresAt;
        this.usageCount = usageCount;
    }
    public ForumAiSuggestion(int id, String questionHash, String question, String suggestions, String aiResponse, Timestamp createdAt, Timestamp expiresAt, int usageCount) {
       this.id = id;
       this.questionHash = questionHash;
       this.question = question;
       this.suggestions = suggestions;
       this.aiResponse = aiResponse;
       this.createdAt = createdAt;
       this.expiresAt = expiresAt;
       this.usageCount = usageCount;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="question_hash", nullable=false, length=64)
    public String getQuestionHash() {
        return this.questionHash;
    }
    
    public void setQuestionHash(String questionHash) {
        this.questionHash = questionHash;
    }

    
    @Column(name="question", nullable=false)
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    
    @Column(name="suggestions", nullable=false, length=1073741824)
    public String getSuggestions() {
        return this.suggestions;
    }
    
    public void setSuggestions(String suggestions) {
        this.suggestions = suggestions;
    }

    
    @Column(name="ai_response")
    public String getAiResponse() {
        return this.aiResponse;
    }
    
    public void setAiResponse(String aiResponse) {
        this.aiResponse = aiResponse;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expires_at", nullable=false, length=19)
    public Timestamp getExpiresAt() {
        return this.expiresAt;
    }
    
    public void setExpiresAt(Timestamp expiresAt) {
        this.expiresAt = expiresAt;
    }

    
    @Column(name="usage_count", nullable=false)
    public int getUsageCount() {
        return this.usageCount;
    }
    
    public void setUsageCount(int usageCount) {
        this.usageCount = usageCount;
    }




}


