package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Timestamp;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name="grade"
    , uniqueConstraints = @UniqueConstraint(columnNames={"assessment_id", "student_id"}) 
)
public class Grade  implements java.io.Serializable {


     private Integer id;
     private Assessment assessment;
     private User userByStudentId;
     private User userByTeacherId;
     private double score;
     private String comment;
     private Timestamp createdAt;
     private Timestamp updatedAt;

    public Grade() {
    }

	
    public Grade(Assessment assessment, User userByStudentId, User userByTeacherId, double score, Timestamp createdAt, Timestamp updatedAt) {
        this.assessment = assessment;
        this.userByStudentId = userByStudentId;
        this.userByTeacherId = userByTeacherId;
        this.score = score;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Grade(Assessment assessment, User userByStudentId, User userByTeacherId, double score, String comment, Timestamp createdAt, Timestamp updatedAt) {
       this.assessment = assessment;
       this.userByStudentId = userByStudentId;
       this.userByTeacherId = userByTeacherId;
       this.score = score;
       this.comment = comment;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="assessment_id", nullable=false)
    public Assessment getAssessment() {
        return this.assessment;
    }
    
    public void setAssessment(Assessment assessment) {
        this.assessment = assessment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public User getUserByStudentId() {
        return this.userByStudentId;
    }
    
    public void setUserByStudentId(User userByStudentId) {
        this.userByStudentId = userByStudentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="teacher_id", nullable=false)
    public User getUserByTeacherId() {
        return this.userByTeacherId;
    }
    
    public void setUserByTeacherId(User userByTeacherId) {
        this.userByTeacherId = userByTeacherId;
    }

    
    @Column(name="score", nullable=false, precision=22)
    public double getScore() {
        return this.score;
    }
    
    public void setScore(double score) {
        this.score = score;
    }

    
    @Column(name="comment")
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }




}


