package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * JobOffer generated by hbm2java
 */
@Entity
@Table(name="job_offer"
)
public class JobOffer  implements java.io.Serializable {


     private int id;
     private User user;
     private String title;
     private String type;
     private String location;
     private String description;
     private String requirements;
     private String status;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private Timestamp publishedAt;
     private Timestamp expiresAt;
     private String requiredSkills;
     private String preferredSkills;
     private Integer minExperienceYears;
     private String minEducation;
     private String requiredLanguages;
     private Set<JobApplication> jobApplications = new HashSet<JobApplication>(0);

    public JobOffer() {
    }

	
    public JobOffer(int id, User user, String title, String type, String description, String status, Timestamp createdAt, Timestamp updatedAt) {
        this.id = id;
        this.user = user;
        this.title = title;
        this.type = type;
        this.description = description;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public JobOffer(int id, User user, String title, String type, String location, String description, String requirements, String status, Timestamp createdAt, Timestamp updatedAt, Timestamp publishedAt, Timestamp expiresAt, String requiredSkills, String preferredSkills, Integer minExperienceYears, String minEducation, String requiredLanguages, Set<JobApplication> jobApplications) {
       this.id = id;
       this.user = user;
       this.title = title;
       this.type = type;
       this.location = location;
       this.description = description;
       this.requirements = requirements;
       this.status = status;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.publishedAt = publishedAt;
       this.expiresAt = expiresAt;
       this.requiredSkills = requiredSkills;
       this.preferredSkills = preferredSkills;
       this.minExperienceYears = minExperienceYears;
       this.minEducation = minEducation;
       this.requiredLanguages = requiredLanguages;
       this.jobApplications = jobApplications;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="partner_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="title", nullable=false, length=255)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="type", nullable=false, length=255)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="location", length=255)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="requirements")
    public String getRequirements() {
        return this.requirements;
    }
    
    public void setRequirements(String requirements) {
        this.requirements = requirements;
    }

    
    @Column(name="status", nullable=false, length=255)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="published_at", length=19)
    public Timestamp getPublishedAt() {
        return this.publishedAt;
    }
    
    public void setPublishedAt(Timestamp publishedAt) {
        this.publishedAt = publishedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expires_at", length=19)
    public Timestamp getExpiresAt() {
        return this.expiresAt;
    }
    
    public void setExpiresAt(Timestamp expiresAt) {
        this.expiresAt = expiresAt;
    }

    
    @Column(name="required_skills", length=1073741824)
    public String getRequiredSkills() {
        return this.requiredSkills;
    }
    
    public void setRequiredSkills(String requiredSkills) {
        this.requiredSkills = requiredSkills;
    }

    
    @Column(name="preferred_skills", length=1073741824)
    public String getPreferredSkills() {
        return this.preferredSkills;
    }
    
    public void setPreferredSkills(String preferredSkills) {
        this.preferredSkills = preferredSkills;
    }

    
    @Column(name="min_experience_years")
    public Integer getMinExperienceYears() {
        return this.minExperienceYears;
    }
    
    public void setMinExperienceYears(Integer minExperienceYears) {
        this.minExperienceYears = minExperienceYears;
    }

    
    @Column(name="min_education", length=50)
    public String getMinEducation() {
        return this.minEducation;
    }
    
    public void setMinEducation(String minEducation) {
        this.minEducation = minEducation;
    }

    
    @Column(name="required_languages", length=1073741824)
    public String getRequiredLanguages() {
        return this.requiredLanguages;
    }
    
    public void setRequiredLanguages(String requiredLanguages) {
        this.requiredLanguages = requiredLanguages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jobOffer")
    public Set<JobApplication> getJobApplications() {
        return this.jobApplications;
    }
    
    public void setJobApplications(Set<JobApplication> jobApplications) {
        this.jobApplications = jobApplications;
    }




}


