package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * MessengerMessages generated by hbm2java
 */
@Entity
@Table(name="messenger_messages"
)
public class MessengerMessages  implements java.io.Serializable {


     private long id;
     private String body;
     private String headers;
     private String queueName;
     private Timestamp createdAt;
     private Timestamp availableAt;
     private Timestamp deliveredAt;

    public MessengerMessages() {
    }

	
    public MessengerMessages(long id, String body, String headers, String queueName, Timestamp createdAt, Timestamp availableAt) {
        this.id = id;
        this.body = body;
        this.headers = headers;
        this.queueName = queueName;
        this.createdAt = createdAt;
        this.availableAt = availableAt;
    }
    public MessengerMessages(long id, String body, String headers, String queueName, Timestamp createdAt, Timestamp availableAt, Timestamp deliveredAt) {
       this.id = id;
       this.body = body;
       this.headers = headers;
       this.queueName = queueName;
       this.createdAt = createdAt;
       this.availableAt = availableAt;
       this.deliveredAt = deliveredAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    @Column(name="body", nullable=false)
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    
    @Column(name="headers", nullable=false)
    public String getHeaders() {
        return this.headers;
    }
    
    public void setHeaders(String headers) {
        this.headers = headers;
    }

    
    @Column(name="queue_name", nullable=false, length=190)
    public String getQueueName() {
        return this.queueName;
    }
    
    public void setQueueName(String queueName) {
        this.queueName = queueName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="available_at", nullable=false, length=19)
    public Timestamp getAvailableAt() {
        return this.availableAt;
    }
    
    public void setAvailableAt(Timestamp availableAt) {
        this.availableAt = availableAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="delivered_at", length=19)
    public Timestamp getDeliveredAt() {
        return this.deliveredAt;
    }
    
    public void setDeliveredAt(Timestamp deliveredAt) {
        this.deliveredAt = deliveredAt;
    }




}


