package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name="module"
)
public class Module  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String periodUnit;
     private int duration;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private Set<BuildProgramModule> buildProgramModules = new HashSet<BuildProgramModule>(0);
     private Set<TeacherClasse> teacherClasses = new HashSet<TeacherClasse>(0);
     private Set<ModuleCourse> moduleCourses = new HashSet<ModuleCourse>(0);
     private Set<ProgramModule> programModules = new HashSet<ProgramModule>(0);
     private Set<ClasseModule> classeModules = new HashSet<ClasseModule>(0);

    public Module() {
    }

	
    public Module(String name, String periodUnit, int duration, Timestamp createdAt, Timestamp updatedAt) {
        this.name = name;
        this.periodUnit = periodUnit;
        this.duration = duration;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Module(String name, String periodUnit, int duration, Timestamp createdAt, Timestamp updatedAt, Set<BuildProgramModule> buildProgramModules, Set<TeacherClasse> teacherClasses, Set<ModuleCourse> moduleCourses, Set<ProgramModule> programModules, Set<ClasseModule> classeModules) {
       this.name = name;
       this.periodUnit = periodUnit;
       this.duration = duration;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.buildProgramModules = buildProgramModules;
       this.teacherClasses = teacherClasses;
       this.moduleCourses = moduleCourses;
       this.programModules = programModules;
       this.classeModules = classeModules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="period_unit", nullable=false, length=255)
    public String getPeriodUnit() {
        return this.periodUnit;
    }
    
    public void setPeriodUnit(String periodUnit) {
        this.periodUnit = periodUnit;
    }

    
    @Column(name="duration", nullable=false)
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="module")
    public Set<BuildProgramModule> getBuildProgramModules() {
        return this.buildProgramModules;
    }
    
    public void setBuildProgramModules(Set<BuildProgramModule> buildProgramModules) {
        this.buildProgramModules = buildProgramModules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="module")
    public Set<TeacherClasse> getTeacherClasses() {
        return this.teacherClasses;
    }
    
    public void setTeacherClasses(Set<TeacherClasse> teacherClasses) {
        this.teacherClasses = teacherClasses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="module")
    public Set<ModuleCourse> getModuleCourses() {
        return this.moduleCourses;
    }
    
    public void setModuleCourses(Set<ModuleCourse> moduleCourses) {
        this.moduleCourses = moduleCourses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="module")
    public Set<ProgramModule> getProgramModules() {
        return this.programModules;
    }
    
    public void setProgramModules(Set<ProgramModule> programModules) {
        this.programModules = programModules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="module")
    public Set<ClasseModule> getClasseModules() {
        return this.classeModules;
    }
    
    public void setClasseModules(Set<ClasseModule> classeModules) {
        this.classeModules = classeModules;
    }




}


