package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Timestamp;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name="profile"
    , uniqueConstraints = @UniqueConstraint(columnNames="user_id") 
)
public class Profile  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String firstName;
     private String lastName;
     private String phone;
     private String photo;
     private String description;
     private Timestamp updatedAt;
     private String avatarFilename;
     private Timestamp avatarUpdatedAt;

    public Profile() {
    }

	
    public Profile(User user, String firstName, String lastName) {
        this.user = user;
        this.firstName = firstName;
        this.lastName = lastName;
    }
    public Profile(User user, String firstName, String lastName, String phone, String photo, String description, Timestamp updatedAt, String avatarFilename, Timestamp avatarUpdatedAt) {
       this.user = user;
       this.firstName = firstName;
       this.lastName = lastName;
       this.phone = phone;
       this.photo = photo;
       this.description = description;
       this.updatedAt = updatedAt;
       this.avatarFilename = avatarFilename;
       this.avatarUpdatedAt = avatarUpdatedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", unique=true, nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="first_name", nullable=false, length=100)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=100)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="phone", length=20)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="photo", length=255)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    
    @Column(name="avatar_filename", length=255)
    public String getAvatarFilename() {
        return this.avatarFilename;
    }
    
    public void setAvatarFilename(String avatarFilename) {
        this.avatarFilename = avatarFilename;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="avatar_updated_at", length=19)
    public Timestamp getAvatarUpdatedAt() {
        return this.avatarUpdatedAt;
    }
    
    public void setAvatarUpdatedAt(Timestamp avatarUpdatedAt) {
        this.avatarUpdatedAt = avatarUpdatedAt;
    }




}


