package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * ProgramChatMessage generated by hbm2java
 */
@Entity
@Table(name="program_chat_message"
)
public class ProgramChatMessage  implements java.io.Serializable {


     private int id;
     private User user;
     private Program program;
     private String type;
     private String content;
     private Timestamp createdAt;

    public ProgramChatMessage() {
    }

	
    public ProgramChatMessage(int id, Program program, String type, String content, Timestamp createdAt) {
        this.id = id;
        this.program = program;
        this.type = type;
        this.content = content;
        this.createdAt = createdAt;
    }
    public ProgramChatMessage(int id, User user, Program program, String type, String content, Timestamp createdAt) {
       this.id = id;
       this.user = user;
       this.program = program;
       this.type = type;
       this.content = content;
       this.createdAt = createdAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sender_id")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="program_id", nullable=false)
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }

    
    @Column(name="type", nullable=false, length=100)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="content", nullable=false)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }




}


