package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Program generated by hbm2java
 */
@Entity
@Table(name="program"
)
public class Program  implements java.io.Serializable {


     private Integer id;
     private String name;
     private byte published;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private Set<BuildProgram> buildPrograms = new HashSet<BuildProgram>(0);
     private Set<ProgramChatMessage> programChatMessages = new HashSet<ProgramChatMessage>(0);
     private Set<ProgramModule> programModules = new HashSet<ProgramModule>(0);
     private Set<Classe> classes = new HashSet<Classe>(0);

    public Program() {
    }

	
    public Program(Integer id, String name, byte published, Timestamp createdAt, Timestamp updatedAt) {
        this.id = id;
        this.name = name;
        this.published = published;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public Program(Integer id, String name, byte published, Timestamp createdAt, Timestamp updatedAt, Set<BuildProgram> buildPrograms, Set<ProgramChatMessage> programChatMessages, Set<ProgramModule> programModules, Set<Classe> classes) {
       this.id = id;
       this.name = name;
       this.published = published;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.buildPrograms = buildPrograms;
       this.programChatMessages = programChatMessages;
       this.programModules = programModules;
       this.classes = classes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="published", nullable=false)
    public byte getPublished() {
        return this.published;
    }
    
    public void setPublished(byte published) {
        this.published = published;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="program")
    public Set<BuildProgram> getBuildPrograms() {
        return this.buildPrograms;
    }
    
    public void setBuildPrograms(Set<BuildProgram> buildPrograms) {
        this.buildPrograms = buildPrograms;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="program")
    public Set<ProgramChatMessage> getProgramChatMessages() {
        return this.programChatMessages;
    }
    
    public void setProgramChatMessages(Set<ProgramChatMessage> programChatMessages) {
        this.programChatMessages = programChatMessages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="program")
    public Set<ProgramModule> getProgramModules() {
        return this.programModules;
    }
    
    public void setProgramModules(Set<ProgramModule> programModules) {
        this.programModules = programModules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="program")
    public Set<Classe> getClasses() {
        return this.classes;
    }
    
    public void setClasses(Set<Classe> classes) {
        this.classes = classes;
    }




}


