package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name="question"
)
public class Question  implements java.io.Serializable {


     private Integer id;
     private Quiz quiz;
     private String type;
     private String questionText;
     private int points;
     private int position;
     private String explanation;
     private Set<Answer> answers = new HashSet<Answer>(0);
     private Set<Choice> choices = new HashSet<Choice>(0);

    public Question() {
    }

	
    public Question(Quiz quiz, String type, String questionText, int points, int position) {
        this.quiz = quiz;
        this.type = type;
        this.questionText = questionText;
        this.points = points;
        this.position = position;
    }
    public Question(Quiz quiz, String type, String questionText, int points, int position, String explanation, Set<Answer> answers, Set<Choice> choices) {
       this.quiz = quiz;
       this.type = type;
       this.questionText = questionText;
       this.points = points;
       this.position = position;
       this.explanation = explanation;
       this.answers = answers;
       this.choices = choices;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="quiz_id", nullable=false)
    public Quiz getQuiz() {
        return this.quiz;
    }
    
    public void setQuiz(Quiz quiz) {
        this.quiz = quiz;
    }

    
    @Column(name="type", nullable=false, length=20)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="question_text", nullable=false)
    public String getQuestionText() {
        return this.questionText;
    }
    
    public void setQuestionText(String questionText) {
        this.questionText = questionText;
    }

    
    @Column(name="points", nullable=false)
    public int getPoints() {
        return this.points;
    }
    
    public void setPoints(int points) {
        this.points = points;
    }

    
    @Column(name="position", nullable=false)
    public int getPosition() {
        return this.position;
    }
    
    public void setPosition(int position) {
        this.position = position;
    }

    
    @Column(name="explanation")
    public String getExplanation() {
        return this.explanation;
    }
    
    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="question")
    public Set<Answer> getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Set<Answer> answers) {
        this.answers = answers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="question")
    public Set<Choice> getChoices() {
        return this.choices;
    }
    
    public void setChoices(Set<Choice> choices) {
        this.choices = choices;
    }




}


