package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

/**
 * Quiz generated by hbm2java
 */
@Entity
@Table(name="quiz"
    , uniqueConstraints = @UniqueConstraint(columnNames="contenu_id") 
)
public class Quiz  implements java.io.Serializable {


     private Integer id;
     private Contenu contenu;
     private String title;
     private String description;
     private Integer passingScore;
     private Integer timeLimit;
     private byte shuffleQuestions;
     private byte shuffleChoices;
     private byte showCorrectAnswers;
     private Set<Question> questions = new HashSet<Question>(0);
     private Set<UserAnswer> userAnswers = new HashSet<UserAnswer>(0);

    public Quiz() {
    }

	
    public Quiz(Contenu contenu, String title, byte shuffleQuestions, byte shuffleChoices, byte showCorrectAnswers) {
        this.contenu = contenu;
        this.title = title;
        this.shuffleQuestions = shuffleQuestions;
        this.shuffleChoices = shuffleChoices;
        this.showCorrectAnswers = showCorrectAnswers;
    }
    public Quiz(Contenu contenu, String title, String description, Integer passingScore, Integer timeLimit, byte shuffleQuestions, byte shuffleChoices, byte showCorrectAnswers, Set<Question> questions, Set<UserAnswer> userAnswers) {
       this.contenu = contenu;
       this.title = title;
       this.description = description;
       this.passingScore = passingScore;
       this.timeLimit = timeLimit;
       this.shuffleQuestions = shuffleQuestions;
       this.shuffleChoices = shuffleChoices;
       this.showCorrectAnswers = showCorrectAnswers;
       this.questions = questions;
       this.userAnswers = userAnswers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contenu_id", unique=true, nullable=false)
    public Contenu getContenu() {
        return this.contenu;
    }
    
    public void setContenu(Contenu contenu) {
        this.contenu = contenu;
    }

    
    @Column(name="title", nullable=false, length=255)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="passing_score")
    public Integer getPassingScore() {
        return this.passingScore;
    }
    
    public void setPassingScore(Integer passingScore) {
        this.passingScore = passingScore;
    }

    
    @Column(name="time_limit")
    public Integer getTimeLimit() {
        return this.timeLimit;
    }
    
    public void setTimeLimit(Integer timeLimit) {
        this.timeLimit = timeLimit;
    }

    
    @Column(name="shuffle_questions", nullable=false)
    public byte getShuffleQuestions() {
        return this.shuffleQuestions;
    }
    
    public void setShuffleQuestions(byte shuffleQuestions) {
        this.shuffleQuestions = shuffleQuestions;
    }

    
    @Column(name="shuffle_choices", nullable=false)
    public byte getShuffleChoices() {
        return this.shuffleChoices;
    }
    
    public void setShuffleChoices(byte shuffleChoices) {
        this.shuffleChoices = shuffleChoices;
    }

    
    @Column(name="show_correct_answers", nullable=false)
    public byte getShowCorrectAnswers() {
        return this.showCorrectAnswers;
    }
    
    public void setShowCorrectAnswers(byte showCorrectAnswers) {
        this.showCorrectAnswers = showCorrectAnswers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="quiz")
    public Set<Question> getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="quiz")
    public Set<UserAnswer> getUserAnswers() {
        return this.userAnswers;
    }
    
    public void setUserAnswers(Set<UserAnswer> userAnswers) {
        this.userAnswers = userAnswers;
    }




}


