package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * Reclamation generated by hbm2java
 */
@Entity
@Table(name="reclamation"
)
public class Reclamation  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Course course;
     private String subject;
     private String description;
     private String status;
     private String adminResponse;
     private Timestamp createdAt;
     private Timestamp resolvedAt;

    public Reclamation() {
    }

	
    public Reclamation(User user, String subject, String description, String status, Timestamp createdAt) {
        this.user = user;
        this.subject = subject;
        this.description = description;
        this.status = status;
        this.createdAt = createdAt;
    }
    public Reclamation(User user, Course course, String subject, String description, String status, String adminResponse, Timestamp createdAt, Timestamp resolvedAt) {
       this.user = user;
       this.course = course;
       this.subject = subject;
       this.description = description;
       this.status = status;
       this.adminResponse = adminResponse;
       this.createdAt = createdAt;
       this.resolvedAt = resolvedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="related_course_id")
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

    
    @Column(name="subject", nullable=false, length=255)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="status", nullable=false, length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="admin_response")
    public String getAdminResponse() {
        return this.adminResponse;
    }
    
    public void setAdminResponse(String adminResponse) {
        this.adminResponse = adminResponse;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="resolved_at", length=19)
    public Timestamp getResolvedAt() {
        return this.resolvedAt;
    }
    
    public void setResolvedAt(Timestamp resolvedAt) {
        this.resolvedAt = resolvedAt;
    }




}


