package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Timestamp;

/**
 * ResetToken generated by hbm2java
 */
@Entity
@Table(name="reset_token"
    , uniqueConstraints = @UniqueConstraint(columnNames="token") 
)
public class ResetToken  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String token;
     private Timestamp expiryDate;
     private Timestamp createdAt;
     private byte used;

    public ResetToken() {
    }

    public ResetToken(User user, String token, Timestamp expiryDate, Timestamp createdAt, byte used) {
       this.user = user;
       this.token = token;
       this.expiryDate = expiryDate;
       this.createdAt = createdAt;
       this.used = used;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="token", unique=true, nullable=false, length=255)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expiry_date", nullable=false, length=19)
    public Timestamp getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(Timestamp expiryDate) {
        this.expiryDate = expiryDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    
    @Column(name="used", nullable=false)
    public byte getUsed() {
        return this.used;
    }
    
    public void setUsed(byte used) {
        this.used = used;
    }




}


