package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Timestamp;

/**
 * StudentClasse generated by hbm2java
 */
@Entity
@Table(name="student_classe"
    , uniqueConstraints = @UniqueConstraint(columnNames={"student_id", "classe_id"}) 
)
public class StudentClasse  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Classe classe;
     private Timestamp enrolledAt;
     private byte isActive;

    public StudentClasse() {
    }

    public StudentClasse(Integer id, User user, Classe classe, Timestamp enrolledAt, byte isActive) {
       this.id = id;
       this.user = user;
       this.classe = classe;
       this.enrolledAt = enrolledAt;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="classe_id", nullable=false)
    public Classe getClasse() {
        return this.classe;
    }
    
    public void setClasse(Classe classe) {
        this.classe = classe;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="enrolled_at", nullable=false, length=19)
    public Timestamp getEnrolledAt() {
        return this.enrolledAt;
    }
    
    public void setEnrolledAt(Timestamp enrolledAt) {
        this.enrolledAt = enrolledAt;
    }

    
    @Column(name="is_active", nullable=false)
    public byte getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(byte isActive) {
        this.isActive = isActive;
    }




}


