package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * TeacherClasse generated by hbm2java
 */
@Entity
@Table(name="teacher_classe"
    , uniqueConstraints = @UniqueConstraint(columnNames={"teacher_id", "classe_id"}) 
)
public class TeacherClasse  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Classe classe;
     private Module module;
     private Timestamp assignedAt;
     private byte isActive;
     private byte hasCreatedModule;
     private Set<ClassMeeting> classMeetings = new HashSet<ClassMeeting>(0);

    public TeacherClasse() {
    }

	
    public TeacherClasse(User user, Classe classe, Timestamp assignedAt, byte isActive, byte hasCreatedModule) {
        this.user = user;
        this.classe = classe;
        this.assignedAt = assignedAt;
        this.isActive = isActive;
        this.hasCreatedModule = hasCreatedModule;
    }
    public TeacherClasse(User user, Classe classe, Module module, Timestamp assignedAt, byte isActive, byte hasCreatedModule, Set<ClassMeeting> classMeetings) {
       this.user = user;
       this.classe = classe;
       this.module = module;
       this.assignedAt = assignedAt;
       this.isActive = isActive;
       this.hasCreatedModule = hasCreatedModule;
       this.classMeetings = classMeetings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="teacher_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="classe_id", nullable=false)
    public Classe getClasse() {
        return this.classe;
    }
    
    public void setClasse(Classe classe) {
        this.classe = classe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="module_id")
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="assigned_at", nullable=false, length=19)
    public Timestamp getAssignedAt() {
        return this.assignedAt;
    }
    
    public void setAssignedAt(Timestamp assignedAt) {
        this.assignedAt = assignedAt;
    }

    
    @Column(name="is_active", nullable=false)
    public byte getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(byte isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="has_created_module", nullable=false)
    public byte getHasCreatedModule() {
        return this.hasCreatedModule;
    }
    
    public void setHasCreatedModule(byte hasCreatedModule) {
        this.hasCreatedModule = hasCreatedModule;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="teacherClasse")
    public Set<ClassMeeting> getClassMeetings() {
        return this.classMeetings;
    }
    
    public void setClassMeetings(Set<ClassMeeting> classMeetings) {
        this.classMeetings = classMeetings;
    }




}


