package entities;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String role;
     private String email;
     private String password;
     private byte isActive;
     private String name;
     private String phone;
     private String profilePic;
     private String location;
     private String skills;
     private String about;
     private byte isVerified;
     private byte needsVerification;
     private Timestamp emailVerifiedAt;
     private String emailVerificationCode;
     private Timestamp codeExpiryDate;
     private byte mustChangePassword;
     private Timestamp tempPasswordGeneratedAt;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private byte faceEnabled;
     private String faceDescriptors;
     private Timestamp faceEnrolledAt;
     private Set<JobOffer> jobOffers = new HashSet<JobOffer>(0);
     private Set<Schedule> schedules = new HashSet<Schedule>(0);
     private Set<FaceVerificationLog> faceVerificationLogs = new HashSet<FaceVerificationLog>(0);
     private Set<UserAnswer> userAnswers = new HashSet<UserAnswer>(0);
     private Set<Profile> profiles = new HashSet<Profile>(0);
     private Set<Assessment> assessments = new HashSet<Assessment>(0);
     private Set<EventParticipation> eventParticipations = new HashSet<EventParticipation>(0);
     private Set<JobApplication> jobApplications = new HashSet<JobApplication>(0);
     private Set<Grade> gradesForStudentId = new HashSet<Grade>(0);
     private Set<DocumentRequest> documentRequests = new HashSet<DocumentRequest>(0);
     private Set<Event> events = new HashSet<Event>(0);
     private Set<StudentClasse> studentClasses = new HashSet<StudentClasse>(0);
     private Set<Reclamation> reclamations = new HashSet<Reclamation>(0);
     private Set<ForumCommentReaction> forumCommentReactions = new HashSet<ForumCommentReaction>(0);
     private Set<TeacherClasse> teacherClasses = new HashSet<TeacherClasse>(0);
     private Set<ProgramChatMessage> programChatMessages = new HashSet<ProgramChatMessage>(0);
     private Set<ForumComment> forumComments = new HashSet<ForumComment>(0);
     private Set<GeneralChatMessage> generalChatMessages = new HashSet<GeneralChatMessage>(0);
     private Set<Grade> gradesForTeacherId = new HashSet<Grade>(0);
     private Set<ResetToken> resetTokens = new HashSet<ResetToken>(0);
     private Set<CourseDocument> courseDocuments = new HashSet<CourseDocument>(0);
     private Set<CustomSkill> customSkills = new HashSet<CustomSkill>(0);
     private Set<ForumTopic> forumTopics = new HashSet<ForumTopic>(0);

    public User() {
    }

	
    public User(String role, String email, String password, byte isActive, byte isVerified, byte needsVerification, byte mustChangePassword, Timestamp createdAt, Timestamp updatedAt, byte faceEnabled) {
        this.role = role;
        this.email = email;
        this.password = password;
        this.isActive = isActive;
        this.isVerified = isVerified;
        this.needsVerification = needsVerification;
        this.mustChangePassword = mustChangePassword;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.faceEnabled = faceEnabled;
    }
    public User(String role, String email, String password, byte isActive, String name, String phone, String profilePic, String location, String skills, String about, byte isVerified, byte needsVerification, Timestamp emailVerifiedAt, String emailVerificationCode, Timestamp codeExpiryDate, byte mustChangePassword, Timestamp tempPasswordGeneratedAt, Timestamp createdAt, Timestamp updatedAt, byte faceEnabled, String faceDescriptors, Timestamp faceEnrolledAt, Set<JobOffer> jobOffers, Set<Schedule> schedules, Set<FaceVerificationLog> faceVerificationLogs, Set<UserAnswer> userAnswers, Set<Profile> profiles, Set<Assessment> assessments, Set<EventParticipation> eventParticipations, Set<JobApplication> jobApplications, Set<Grade> gradesForStudentId, Set<DocumentRequest> documentRequests, Set<Event> events, Set<StudentClasse> studentClasses, Set<Reclamation> reclamations, Set<ForumCommentReaction> forumCommentReactions, Set<TeacherClasse> teacherClasses, Set<ProgramChatMessage> programChatMessages, Set<ForumComment> forumComments, Set<GeneralChatMessage> generalChatMessages, Set<Grade> gradesForTeacherId, Set<ResetToken> resetTokens, Set<CourseDocument> courseDocuments, Set<CustomSkill> customSkills, Set<ForumTopic> forumTopics) {
       this.role = role;
       this.email = email;
       this.password = password;
       this.isActive = isActive;
       this.name = name;
       this.phone = phone;
       this.profilePic = profilePic;
       this.location = location;
       this.skills = skills;
       this.about = about;
       this.isVerified = isVerified;
       this.needsVerification = needsVerification;
       this.emailVerifiedAt = emailVerifiedAt;
       this.emailVerificationCode = emailVerificationCode;
       this.codeExpiryDate = codeExpiryDate;
       this.mustChangePassword = mustChangePassword;
       this.tempPasswordGeneratedAt = tempPasswordGeneratedAt;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.faceEnabled = faceEnabled;
       this.faceDescriptors = faceDescriptors;
       this.faceEnrolledAt = faceEnrolledAt;
       this.jobOffers = jobOffers;
       this.schedules = schedules;
       this.faceVerificationLogs = faceVerificationLogs;
       this.userAnswers = userAnswers;
       this.profiles = profiles;
       this.assessments = assessments;
       this.eventParticipations = eventParticipations;
       this.jobApplications = jobApplications;
       this.gradesForStudentId = gradesForStudentId;
       this.documentRequests = documentRequests;
       this.events = events;
       this.studentClasses = studentClasses;
       this.reclamations = reclamations;
       this.forumCommentReactions = forumCommentReactions;
       this.teacherClasses = teacherClasses;
       this.programChatMessages = programChatMessages;
       this.forumComments = forumComments;
       this.generalChatMessages = generalChatMessages;
       this.gradesForTeacherId = gradesForTeacherId;
       this.resetTokens = resetTokens;
       this.courseDocuments = courseDocuments;
       this.customSkills = customSkills;
       this.forumTopics = forumTopics;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="role", nullable=false, length=50)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    
    @Column(name="email", unique=true, nullable=false, length=180)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=255)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="is_active", nullable=false)
    public byte getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(byte isActive) {
        this.isActive = isActive;
    }

    
    @Column(name="name", length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="phone", length=50)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="profile_pic", length=255)
    public String getProfilePic() {
        return this.profilePic;
    }
    
    public void setProfilePic(String profilePic) {
        this.profilePic = profilePic;
    }

    
    @Column(name="location", length=255)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="skills", length=1073741824)
    public String getSkills() {
        return this.skills;
    }
    
    public void setSkills(String skills) {
        this.skills = skills;
    }

    
    @Column(name="about")
    public String getAbout() {
        return this.about;
    }
    
    public void setAbout(String about) {
        this.about = about;
    }

    
    @Column(name="is_verified", nullable=false)
    public byte getIsVerified() {
        return this.isVerified;
    }
    
    public void setIsVerified(byte isVerified) {
        this.isVerified = isVerified;
    }

    
    @Column(name="needs_verification", nullable=false)
    public byte getNeedsVerification() {
        return this.needsVerification;
    }
    
    public void setNeedsVerification(byte needsVerification) {
        this.needsVerification = needsVerification;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="email_verified_at", length=19)
    public Timestamp getEmailVerifiedAt() {
        return this.emailVerifiedAt;
    }
    
    public void setEmailVerifiedAt(Timestamp emailVerifiedAt) {
        this.emailVerifiedAt = emailVerifiedAt;
    }

    
    @Column(name="email_verification_code", length=100)
    public String getEmailVerificationCode() {
        return this.emailVerificationCode;
    }
    
    public void setEmailVerificationCode(String emailVerificationCode) {
        this.emailVerificationCode = emailVerificationCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="code_expiry_date", length=19)
    public Timestamp getCodeExpiryDate() {
        return this.codeExpiryDate;
    }
    
    public void setCodeExpiryDate(Timestamp codeExpiryDate) {
        this.codeExpiryDate = codeExpiryDate;
    }

    
    @Column(name="must_change_password", nullable=false)
    public byte getMustChangePassword() {
        return this.mustChangePassword;
    }
    
    public void setMustChangePassword(byte mustChangePassword) {
        this.mustChangePassword = mustChangePassword;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="temp_password_generated_at", length=19)
    public Timestamp getTempPasswordGeneratedAt() {
        return this.tempPasswordGeneratedAt;
    }
    
    public void setTempPasswordGeneratedAt(Timestamp tempPasswordGeneratedAt) {
        this.tempPasswordGeneratedAt = tempPasswordGeneratedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    
    @Column(name="face_enabled", nullable=false)
    public byte getFaceEnabled() {
        return this.faceEnabled;
    }
    
    public void setFaceEnabled(byte faceEnabled) {
        this.faceEnabled = faceEnabled;
    }

    
    @Column(name="face_descriptors", length=1073741824)
    public String getFaceDescriptors() {
        return this.faceDescriptors;
    }
    
    public void setFaceDescriptors(String faceDescriptors) {
        this.faceDescriptors = faceDescriptors;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="face_enrolled_at", length=19)
    public Timestamp getFaceEnrolledAt() {
        return this.faceEnrolledAt;
    }
    
    public void setFaceEnrolledAt(Timestamp faceEnrolledAt) {
        this.faceEnrolledAt = faceEnrolledAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<JobOffer> getJobOffers() {
        return this.jobOffers;
    }
    
    public void setJobOffers(Set<JobOffer> jobOffers) {
        this.jobOffers = jobOffers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Schedule> getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set<Schedule> schedules) {
        this.schedules = schedules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<FaceVerificationLog> getFaceVerificationLogs() {
        return this.faceVerificationLogs;
    }
    
    public void setFaceVerificationLogs(Set<FaceVerificationLog> faceVerificationLogs) {
        this.faceVerificationLogs = faceVerificationLogs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<UserAnswer> getUserAnswers() {
        return this.userAnswers;
    }
    
    public void setUserAnswers(Set<UserAnswer> userAnswers) {
        this.userAnswers = userAnswers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Profile> getProfiles() {
        return this.profiles;
    }
    
    public void setProfiles(Set<Profile> profiles) {
        this.profiles = profiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Assessment> getAssessments() {
        return this.assessments;
    }
    
    public void setAssessments(Set<Assessment> assessments) {
        this.assessments = assessments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<EventParticipation> getEventParticipations() {
        return this.eventParticipations;
    }
    
    public void setEventParticipations(Set<EventParticipation> eventParticipations) {
        this.eventParticipations = eventParticipations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<JobApplication> getJobApplications() {
        return this.jobApplications;
    }
    
    public void setJobApplications(Set<JobApplication> jobApplications) {
        this.jobApplications = jobApplications;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByStudentId")
    public Set<Grade> getGradesForStudentId() {
        return this.gradesForStudentId;
    }
    
    public void setGradesForStudentId(Set<Grade> gradesForStudentId) {
        this.gradesForStudentId = gradesForStudentId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<DocumentRequest> getDocumentRequests() {
        return this.documentRequests;
    }
    
    public void setDocumentRequests(Set<DocumentRequest> documentRequests) {
        this.documentRequests = documentRequests;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Event> getEvents() {
        return this.events;
    }
    
    public void setEvents(Set<Event> events) {
        this.events = events;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<StudentClasse> getStudentClasses() {
        return this.studentClasses;
    }
    
    public void setStudentClasses(Set<StudentClasse> studentClasses) {
        this.studentClasses = studentClasses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Reclamation> getReclamations() {
        return this.reclamations;
    }
    
    public void setReclamations(Set<Reclamation> reclamations) {
        this.reclamations = reclamations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<ForumCommentReaction> getForumCommentReactions() {
        return this.forumCommentReactions;
    }
    
    public void setForumCommentReactions(Set<ForumCommentReaction> forumCommentReactions) {
        this.forumCommentReactions = forumCommentReactions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<TeacherClasse> getTeacherClasses() {
        return this.teacherClasses;
    }
    
    public void setTeacherClasses(Set<TeacherClasse> teacherClasses) {
        this.teacherClasses = teacherClasses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<ProgramChatMessage> getProgramChatMessages() {
        return this.programChatMessages;
    }
    
    public void setProgramChatMessages(Set<ProgramChatMessage> programChatMessages) {
        this.programChatMessages = programChatMessages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<ForumComment> getForumComments() {
        return this.forumComments;
    }
    
    public void setForumComments(Set<ForumComment> forumComments) {
        this.forumComments = forumComments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<GeneralChatMessage> getGeneralChatMessages() {
        return this.generalChatMessages;
    }
    
    public void setGeneralChatMessages(Set<GeneralChatMessage> generalChatMessages) {
        this.generalChatMessages = generalChatMessages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByTeacherId")
    public Set<Grade> getGradesForTeacherId() {
        return this.gradesForTeacherId;
    }
    
    public void setGradesForTeacherId(Set<Grade> gradesForTeacherId) {
        this.gradesForTeacherId = gradesForTeacherId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<ResetToken> getResetTokens() {
        return this.resetTokens;
    }
    
    public void setResetTokens(Set<ResetToken> resetTokens) {
        this.resetTokens = resetTokens;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<CourseDocument> getCourseDocuments() {
        return this.courseDocuments;
    }
    
    public void setCourseDocuments(Set<CourseDocument> courseDocuments) {
        this.courseDocuments = courseDocuments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<CustomSkill> getCustomSkills() {
        return this.customSkills;
    }
    
    public void setCustomSkills(Set<CustomSkill> customSkills) {
        this.customSkills = customSkills;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<ForumTopic> getForumTopics() {
        return this.forumTopics;
    }
    
    public void setForumTopics(Set<ForumTopic> forumTopics) {
        this.forumTopics = forumTopics;
    }




}


