package entities;
// Generated Apr 7, 2026, 3:00:13 PM by Hibernate Tools 6.6.42.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * UserAnswer generated by hbm2java
 */
@Entity
@Table(name="user_answer"
    , uniqueConstraints = @UniqueConstraint(columnNames={"user_id", "quiz_id"}) 
)
public class UserAnswer  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Quiz quiz;
     private Integer score;
     private Integer totalPoints;
     private Timestamp startedAt;
     private Timestamp completedAt;
     private byte isPassed;
     private byte isCheated;
     private int tabSwitchCount;
     private Set<Answer> answers = new HashSet<Answer>(0);

    public UserAnswer() {
    }

	
    public UserAnswer(User user, Quiz quiz, byte isPassed, byte isCheated, int tabSwitchCount) {
        this.user = user;
        this.quiz = quiz;
        this.isPassed = isPassed;
        this.isCheated = isCheated;
        this.tabSwitchCount = tabSwitchCount;
    }
    public UserAnswer(User user, Quiz quiz, Integer score, Integer totalPoints, Timestamp startedAt, Timestamp completedAt, byte isPassed, byte isCheated, int tabSwitchCount, Set<Answer> answers) {
       this.user = user;
       this.quiz = quiz;
       this.score = score;
       this.totalPoints = totalPoints;
       this.startedAt = startedAt;
       this.completedAt = completedAt;
       this.isPassed = isPassed;
       this.isCheated = isCheated;
       this.tabSwitchCount = tabSwitchCount;
       this.answers = answers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="quiz_id", nullable=false)
    public Quiz getQuiz() {
        return this.quiz;
    }
    
    public void setQuiz(Quiz quiz) {
        this.quiz = quiz;
    }

    
    @Column(name="score")
    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }

    
    @Column(name="total_points")
    public Integer getTotalPoints() {
        return this.totalPoints;
    }
    
    public void setTotalPoints(Integer totalPoints) {
        this.totalPoints = totalPoints;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="started_at", length=19)
    public Timestamp getStartedAt() {
        return this.startedAt;
    }
    
    public void setStartedAt(Timestamp startedAt) {
        this.startedAt = startedAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="completed_at", length=19)
    public Timestamp getCompletedAt() {
        return this.completedAt;
    }
    
    public void setCompletedAt(Timestamp completedAt) {
        this.completedAt = completedAt;
    }

    
    @Column(name="is_passed", nullable=false)
    public byte getIsPassed() {
        return this.isPassed;
    }
    
    public void setIsPassed(byte isPassed) {
        this.isPassed = isPassed;
    }

    
    @Column(name="is_cheated", nullable=false)
    public byte getIsCheated() {
        return this.isCheated;
    }
    
    public void setIsCheated(byte isCheated) {
        this.isCheated = isCheated;
    }

    
    @Column(name="tab_switch_count", nullable=false)
    public int getTabSwitchCount() {
        return this.tabSwitchCount;
    }
    
    public void setTabSwitchCount(int tabSwitchCount) {
        this.tabSwitchCount = tabSwitchCount;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userAnswer")
    public Set<Answer> getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Set<Answer> answers) {
        this.answers = answers;
    }




}


