package entities.forum;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import entities.User;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Timestamp;

/**
 * ForumCommentReaction generated by hbm2java
 */
@Entity
@Table(name="forum_comment_reaction"
    , uniqueConstraints = @UniqueConstraint(columnNames={"user_id", "comment_id"}) 
)
public class ForumCommentReaction  implements java.io.Serializable {


     private int id;
     private User user;
     private ForumComment forumComment;
     private String type;
     private Timestamp createdAt;

    public ForumCommentReaction() {
    }

    public ForumCommentReaction(int id, User user, ForumComment forumComment, String type, Timestamp createdAt) {
       this.id = id;
       this.user = user;
       this.forumComment = forumComment;
       this.type = type;
       this.createdAt = createdAt;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="comment_id", nullable=false)
    public ForumComment getForumComment() {
        return this.forumComment;
    }
    
    public void setForumComment(ForumComment forumComment) {
        this.forumComment = forumComment;
    }

    
    @Column(name="type", nullable=false, length=10)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }




}


