package entities.forum;
// Generated 11 avr. 2026, 15:58:41 by Hibernate Tools 6.6.42.Final


import entities.User;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * ForumComment generated by hbm2java
 */
@Entity
@Table(name="forum_comment"
)
public class ForumComment  implements java.io.Serializable {


     private int id;
     private User user;
     private ForumTopic forumTopic;
     private ForumComment forumComment;
     private String content;
     private boolean isTeacherResponse;
     private boolean isAccepted;
     private Timestamp createdAt;
     private Timestamp updatedAt;
     private Set<ForumComment> forumComments = new HashSet<ForumComment>(0);
     private Set<ForumCommentReaction> forumCommentReactions = new HashSet<ForumCommentReaction>(0);

    public ForumComment() {
    }

	
    public ForumComment(int id, User user, ForumTopic forumTopic, String content, boolean isTeacherResponse, boolean isAccepted, Timestamp createdAt, Timestamp updatedAt) {
        this.id = id;
        this.user = user;
        this.forumTopic = forumTopic;
        this.content = content;
        this.isTeacherResponse = isTeacherResponse;
        this.isAccepted = isAccepted;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
    public ForumComment(int id, User user, ForumTopic forumTopic, ForumComment forumComment, String content, boolean isTeacherResponse, boolean isAccepted, Timestamp createdAt, Timestamp updatedAt, Set<ForumComment> forumComments, Set<ForumCommentReaction> forumCommentReactions) {
       this.id = id;
       this.user = user;
       this.forumTopic = forumTopic;
       this.forumComment = forumComment;
       this.content = content;
       this.isTeacherResponse = isTeacherResponse;
       this.isAccepted = isAccepted;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.forumComments = forumComments;
       this.forumCommentReactions = forumCommentReactions;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="author_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="topic_id", nullable=false)
    public ForumTopic getForumTopic() {
        return this.forumTopic;
    }
    
    public void setForumTopic(ForumTopic forumTopic) {
        this.forumTopic = forumTopic;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent_id")
    public ForumComment getForumComment() {
        return this.forumComment;
    }
    
    public void setForumComment(ForumComment forumComment) {
        this.forumComment = forumComment;
    }

    
    @Column(name="content", nullable=false)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    
    @Column(name="is_teacher_response", nullable=false)
    public boolean isIsTeacherResponse() {
        return this.isTeacherResponse;
    }
    
    public void setIsTeacherResponse(boolean isTeacherResponse) {
        this.isTeacherResponse = isTeacherResponse;
    }

    
    @Column(name="is_accepted", nullable=false)
    public boolean isIsAccepted() {
        return this.isAccepted;
    }
    
    public void setIsAccepted(boolean isAccepted) {
        this.isAccepted = isAccepted;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", nullable=false, length=19)
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", nullable=false, length=19)
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="forumComment")
    public Set<ForumComment> getForumComments() {
        return this.forumComments;
    }
    
    public void setForumComments(Set<ForumComment> forumComments) {
        this.forumComments = forumComments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="forumComment")
    public Set<ForumCommentReaction> getForumCommentReactions() {
        return this.forumCommentReactions;
    }
    
    public void setForumCommentReactions(Set<ForumCommentReaction> forumCommentReactions) {
        this.forumCommentReactions = forumCommentReactions;
    }




}


